-- require("mason").setup({
--   ui = {
--     icons = {
--       package_installed = "✓",
--       package_pending = "➜",
--       package_uninstalled = "✗",
--     },
--   },
-- })
--
-- require("mason-lspconfig").setup({
--   -- 确保安装，根据需要填写
--   ensure_installed = {
--     "clangd",
--     "clang-format",
--     "cpptools",
--     "codelldb",
--     "lua-language-server",
--     "shellcheck",
--     "shfmt",
--     "stylua",
--   },
-- })
